version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    versioning-strategy: increase

  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    ignore:
      # Lock MongoDB to current major.minor version (5.0.x)
      - dependency-name: "mongo"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      # Lock PostgreSQL to current major.minor version (16.6.x)
      - dependency-name: "postgres"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
